# .github/workflows/coverage-deploy.yml
name: "Coverage and Deploy"

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Restore
      run: dotnet restore CDBCalc.sln

    - name: Build and Test
      run: dotnet build CDBCalc.sln --configuration Release

    - name: Generate Coverage Report + Badge
      run: |
        mkdir -p reports
        reportgenerator \
          -reports:"tests/unit/**/**/TestResults/coverage.xml" \
          -targetdir:"reports" \
          -reporttypes:"Html;TextSummary;Badge" \
          -title:"CDBCalculator - Cobertura Consolidada"

    - name: Save Coverage Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: reports/

  deploy:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
    - name: Download coverage report
      uses: actions/download-artifact@v4
      with:
        name: coverage-report
        path: reports

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: reports
        publish_branch: gh-pages